### ISSUE TITLE
Support for <Label.Text> is missing

### ISSUE THREAD

**Issue by djshaw01** [UXDivers/Gorilla-Player-Support-And-Issues#14]
Labels like 

`<Label HorizontalOptions="CenterAndExpand" VerticalOptions="FillAndExpand" FontSize="Micro" Text="TERMS AND CONDITIONS FOR USE OF THIS APPLICATION AND NON-DISCLOSURE AGREEMENT" />`  work fine, 
while
`<Label HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand" FontSize="Micro">
  <Label.Text>This is a confidential and proprietary application owned solely by ................
 etc
 etc
 </Label.Text>
</Label>`
do not.

**Comment by diego5** [comment]
This was fixed in v0.8.3.
