### ISSUE TITLE
Image resources not found correctly, when reference to PCL library has no GUID

### ISSUE THREAD

**Issue by jonashjordie** [UXDivers/Gorilla-Player-Support-And-Issues#19]
Some of my projects does not have a project reference GUID, for example a reference from the Android project to the PCL project, like below, which results in image resources are not located correctly by Gorilla. (I guess it uses the GUID to locate the resources). 

The projects can compile and deploy fine, so the Project GUID reference may be something optional in Visual Studio/Xamarin Studio, maybe depending on the version the project was created with, since it was not in my projects?

````xml
<ItemGroup>
    <ProjectReference Include="..\TestApp\TestApp.csproj">
      <Name>TestApp</Name>
    </ProjectReference>
  </ItemGroup>
````

**Workaround:** as soon as I remove the project reference, and re-add it in Xamarin, it gets the project GUID added, and then the images are displayed:

````xml
<ItemGroup>
    <ProjectReference Include="..\TestApp\TestApp.csproj">
      <Project>{7A1A9AD6-5F93-4FDF-9B8C-0C61CF91B597}</Project>
      <Name>TestApp</Name>
    </ProjectReference>
  </ItemGroup>
````

Either Gorilla should (preferably) be able to find the project reference by name, or it should at least display clear instructions on re-adding the project reference to fix it. Right now it only sometimes displays an error like this: "Missing GUID in project reference" - which took me a while to figure out what that meant, and it was only displayed when there were other errors on the page at the same time.

Otherwise I am VERY excited about your product, it feels quite solid and well-designed and I really feel it is the missing link, when designing XAML pages, I feel I have been fumbling in the dark when designing XAML the past year, so I look much forward to your Visual Studio plugin :-D

**Comment by LeoHere** [comment]
Thanks for your feedback!

Starting in version (0.8.2, our next version) were removed as a mean to identifying projects and their relations. As you said, GUIDs can't always be trusted for that task. We switched to name/path based identification. We didn't test the specific scenario you are describing here but it should be fixed.

0.8.2 also comes with VS support too, hold on, we are close!
