### ISSUE TITLE
Error occurred while setting Gorilla Target XAML (Xamarin Studio on Mac OSX)

### ISSUE THREAD

**Issue by raechten** [UXDivers/Gorilla-Player-Support-And-Issues#33]
![schermafdruk 2016-02-02 12 48 17](https://cloud.githubusercontent.com/assets/1953088/12762194/51a8ed2a-c9ab-11e5-8141-ae6b58288378.png)

I've installed Gorilla and can run your sample app without issue, but when I try to run it with my own solution, I get the aforementioned error on all XAML. I took the simplest one (actually a remnant that shouldn't even be in the solution anymore) and brought it back to the most basic version I could think of (took out all the colors, buttons, images, etc.) and still I get this error.

Can you tell me where I can find the logs, so I can further investigate?

**Comment by jpbrocca** [comment]
Hi @reachten, thanks for helping us!

This error could be related to a shared project _currently only PCL is supported-, but to make sure you can get the logs from this folder:

~~~
Users\<YOUR_USER>\.gorilla\logs
~~~

If you could zip all of them and attach on this issue that would be of very much help!

Thank you.

**Comment by raechten** [comment]
Alright. That is it then. I am indeed using a shared project. Any idea if/when shared projects will be supported?

Thanks for the quick response.

**Comment by jpbrocca** [comment]
You are welcome :)

Well, this is something that other users also asked for but the most common requested feature so far is:

https://github.com/UXDivers/Gorilla-Player-Support-And-Issues/issues/12

In next version we will evaluate if we could add support for shared projects though.

Meanwhile maybe you could create a parallel project just to preview your XAML in Gorilla then copy your code to your original project.

I know it is not the best but at least I have heard that workaround from other users.

Cheers!
JP

**Comment by raechten** [comment]
Excellent. I'll try that and will keep my eye out for a future release with Shared Project support. Keep up the good work.

**Comment by jpbrocca** [comment]
Thank you! :D
