### ISSUE TITLE
Not working out of the box on iOS with latest Xamarin Studio & Nuget Packages

### ISSUE THREAD

**Issue by jasonCodesAway** [UXDivers/Gorilla-Player-Support-And-Issues#35]
Using Xamarin Studio 5.10.2 (build 56) and Xamarin Forms 2.0.1.6565 I deployed Gorilla Player to my iPhone 4 simulator, no problem, connects and everything. I then open up the 'MyCoolCompanyApp' solution and update nuget packages and I see that it says "MyCoolCompanyPage.xaml (Gorilla)" in XS, I start up the iOS project, edit the MyCoolCompanyPage.xaml by adding text and adding/removing elements, but no changes are visible in the rendered MyCoolCompanyPage.xaml on the iPhone 4s iOS 9.2 simulator :(.

**Comment by jpbrocca** [comment]
Hi @jasonCodesAway, thanks for hepling us to improve Gorilla Player!

Could you attach your logs to this thread? (you will need to make a .zip file).

You can find the logs in the following folder:

~~~
Users\YOUR_USER\.gorilla\logs
~~~

Regards and thanks,
JP

**Comment by jasonCodesAway** [comment]
Nice! I was just doing that. I tried to get it to work for longer than I care to admit, so I blew away the old logs, restarted Xamarin Studio, and stepped through it just once (deployed the Gorilla Player and opened up and played the "MyCoolCompanyPage.xaml" solution, but now I only get one log with very little. It's 'xamarinStudio.log' and it only contains this:

GorillaXS Verbose: 0 : config.json content is {"serverName":"Gorilla on Jasons-Mac-mini.local"}
    ProcessId=45634
    DateTime=2016-02-11T14:30:17.5990690Z
    Timestamp=930971447248
GorillaXS Information: 1 : Starting Addin Initialization
    ProcessId=45634
    DateTime=2016-02-11T14:30:17.7110940Z
    Timestamp=930972561033
GorillaXS Information: 2 : Preferences: Host (localhost), Port (9014), UseLocalGorillaConfiguration (True), FollowMe (False), FirstTime (False)
    ProcessId=45634
    DateTime=2016-02-11T14:30:17.7125390Z
    Timestamp=930972575466
GorillaXS Information: 3 : Ending Addin Initialization
    ProcessId=45634
    DateTime=2016-02-11T14:30:18.0405630Z
    Timestamp=930975865466

**Comment by jasonCodesAway** [comment]
I still had the gorilla logs in my rubbish...but these logs are full of me trying many different things to see if I could get it to work so I'm not so sure how helpful they'll be.
[Gorilla Logs.zip](https://github.com/UXDivers/Gorilla-Player-Support-And-Issues/files/126500/Gorilla.Logs.zip)

**Comment by jasonCodesAway** [comment]
I think what you guys are doing is awesome, so please let me know if I can help in anyway. I'd be glad to screen share. I did try resetting the iOS simulator, closing XS, and restarting the whole process but I'm not seeing any new gorilla logs get generated for whatever reason. If you'd like me to uninstall and reinstall let me know and I'll try that as well, to see if I can get fresh logs.

**Comment by jpbrocca** [comment]
Great, thanks!
We will review those just in case :P
But if you could start from scratch that would be a great help.

Also could you add the following after installing and before you start using Gorilla:

~~~
"logLevel": "debug"
~~~

To your 

~~~
config.json
~~~

file located on logs parent folder?

Thanks a lot!!
JP

**Comment by jasonCodesAway** [comment]
[Gorilla Take4.zip](https://github.com/UXDivers/Gorilla-Player-Support-And-Issues/files/127109/Gorilla.Take4.zip)

I believe the only thing that might make my mac special is that I did at one point install the Xamarin 6 preview edition (which also means updating to mono 4.2.2), but I've subsequently gone back to 5.10.2.

Here is what I did (I'm breaking it down because I don't see any debug log messages show up):
- I uninstalled GP by dragging it from Apps to Rubbish
- Went into XS and using the Add-In Manager uinstalled the GP extension
- Closed out Xamarin Studio
- Reinstalled gorilla-player_0.8.2.dmg
- Got to the "Installation Finished!" "Walkthrough" screen
- Exited Gorill Player (Top-level menu, Gorilla Player -> Quit)
- Modified my 'config.json' to this:
{
	"serverName":"Gorilla on Jasons-Mac-mini.local",
	"logLevel":"debug"
}
- Opened Gorilla Player back up, clicked on the "Getting Started Walkthrough" menu item, and hit 'Go to next step' to go to Step 2: "Deploying Gorilla Player on your devices"
- I reset my iPhone 6s simulator
- Clicked "opening Player.sln"
- Bypassed an unrelated Xamarin Studio issue where its confused about my android trial (completely unrelated)
- Clicked Play to launch 'Player.iOS' after all packages were restored (not updated)
- I see Gorilla Player on the iOS simulator, looks good. It says "Connected!" and all that jazz.
- Back on the Walkthrough UI I hit "go to next step" and then "Open MyCoolCompanyApp.sln" which closes out Player.iOS and opens "MyCoolCompanyApp.sln"
- Right click 'MyCoolCompany.iOS' and click "Set as startup project"
- Open "MyCoolCompanyApp", find "MyCoolCompanyPage.xaml", right click, and select "Stick gorilla to this", then I see "MyCoolCompanyPage.xaml (Gorilla)"
- Hit play (all packages have restored by now, no updates)
- I see the "My Cool Company Name" XAML showing up in the iPhone 6s simulator. 
- I edited the XAML like a madman, adding, editing, and removing elements. No changes show up in the simulator. Argh.

**Comment by jpbrocca** [comment]
Wow, that was the mother of all the detailed steps in history! Thanks for taking the time to do this!
We will review it in detail.

If we don't find any clue, then we could coordinate an online meeting or something so you could show us everything then we could try to find out what could be happening.

Thanks again!
JP

**Comment by jasonCodesAway** [comment]
Can you tell I can't wait to get this to work :) :) :) Today and tomorrow I'm working on this app all day, so if screen sharing would help those are good days. Thank you!

**Comment by jpbrocca** [comment]
Hi Jason, 
can you write me an email to jpbrocca@uxdivers.com so we can coordinate better?
Thanks a lot!
JP

**Comment by LeoHere** [comment]
Hi Jason,

On step 17, when you said "Hit Play" you mean that you actually run MyCoolCompanyApp? 

If that is the case (which I think it is based on the logs you sent) that explains why it is not working.

There is no need to hit play. 

The steps you should follow are:
- open Gorilla on the simulator and make sure it is in connected state
- open my cool company solution
- open the file you want to preview. If you are in "Follow me" mode that should be enough, the player should preview the xaml file. If you make changes you will see those changes in the player. If you are not using the follow me, you should set the stick to this xaml. After that you should be ready to go.

Hope it helps and thanks for your feedback.

**Comment by jasonCodesAway** [comment]
Ohhh wow! That's how it works. I thought I'd have to run my solution to
edit my XAML. Gorilla Player acts like a host for my XAML. It's working
perfectly then, thank you!

**Comment by jasonCodesAway** [comment]
Thank you so much for the help!

Unfortunately the preview isn't that great, my app is previewed on the left
and actually run on the right. I lose styles and images (we use SVGs) on
the left. Hopefully a new version will fix this - I'll keep following
Gorilla Player's progress.


​
​

**Comment by jpbrocca** [comment]
Hi Jason,
I am a little bit lost with your last comment...what do you mean with:

> my app is previewed on the left
and actually run on the right. I lose styles and images (we use SVGs) on
the left.

?

Maybe you could attach a screen capture to help me understand what you mean ?

You are supposed to preview styles and common images -supported by Xamarin Forms-...more complex things like custom renderers will be possible to be previewed with Gorilla SDK.

Thanks,
JP

**Comment by jpbrocca** [comment]
Also, these videos could help:

**How to preview XAML Resources on Gorilla Player**
https://www.youtube.com/watch?v=yHYylivYxyo

**Previewing XAML for Xamarin Forms apps on multiple devices**
https://www.youtube.com/watch?v=Ss5kNbavtnM

Best,
JP

**Comment by jasonCodesAway** [comment]
That's interesting. Gmail says I sent two inline pictures, side-by-side,
and I can see them in the e-mail above. Tomorrow I'll create them as
attachments instead. Thanks for the video likes, I'll look at those
tomorrow too. I look forward to using Gorilla Player, nice work, especially
for version 0.82!

**Comment by jpbrocca** [comment]
No worries Jason ;)

If you want to forward that email directly to my email address -if that is easier for you- then just do it :)
It seems when you reply to Github's thread through email you only can include text but no images.

Best,
JP
