### ISSUE TITLE
Server log location not in wiki

### ISSUE THREAD

**Issue by WillemMali** [UXDivers/Gorilla-Player-Support-And-Issues#37]
As the app crashes when something's wrong with my xaml (which happens all the time) I really need to see the server log to find out what's the issue. It'd be a great help if the location of the server log was well-documented.

I don't personally know the location of the log (I couldn't find it) so maybe a dev could comment?

**Comment by jpbrocca** [comment]
Hi :)
You are absolutely right and thanks for letting me know this omission!

I have just created a page on the wiki with that info:
https://github.com/UXDivers/Gorilla-Player-Support-And-Issues/wiki/Gorilla-Player-logs-location

Regards and thanks,
JP

**Comment by WillemMali** [comment]
Awesome, thanks for the quick response!

**Comment by jpbrocca** [comment]
Thanks for helping us to make a better product :)

By the way, Gorilla should not crash that frequent and you should see a message from Gorilla catching errors or explaining what he did to make the preview available.

If you could attach a project or a XAML file which is causing this crash and also the log files that would be of much help!

Thanks!
JP

**Comment by WillemMali** [comment]
No problem, it's in my own interest as well ;)

The error the app gave me was "XAML: One of the identified items was in an
invalid format."

The XAML for the page is:

<?xml version="1.0" encoding="utf-8" ?>
<ContentPage
    xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    x:Class="Test.TestView1"
    Title="Test">
    <Grid>
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="*" />
            <ColumnDefinition Width="*" />
            <ColumnDefinition Width="*" />
            <ColumnDefinition Width="*" />
            <ColumnDefinition Width="*" />
            <ColumnDefinition Width="*" />
        </Grid.ColumnDefinitions>
        <Grid.RowDefinitions>
            <RowDefinition Height="*" />
            <RowDefinition Height="80%" />
            <RowDefinition Height="*" />
        </Grid.RowDefinitions>
        <Button Grid.Column="0" Grid.Row="0" Grid.ColumnSpan="2"></Button>
        <Button Grid.Column="2" Grid.Row="0" Grid.ColumnSpan="2"></Button>
        <Button Grid.Column="4" Grid.Row="0" Grid.ColumnSpan="2"></Button>
    </Grid>
</ContentPage>

The Grid element seems to be the one crashing your compiler; if you
removethe Grid.ColumnDefinitions and Grid.RowDefinitions (and everything
inside) it still crashes.

The relevant line in the log is this:

{"level":"error","message":"Gorilla Server: error: Client reported error
Sender=null, When={0:02/12/16 12:07:52 +01:00}, Context=XAML: One of the
identified items was in an invalid format., ExceptionMessage=Exception has
been thrown by the target of an invocation.,
ExceptionType=System.Reflection.TargetInvocationException,
ExceptionStackTrace=  at System.Reflection.MonoMethod.Invoke (System.Object
obj, BindingFlags invokeAttr, System.Reflection.Binder binder,
System.Object[] parameters, System.Globalization.CultureInfo culture)
<0x7f95a40040 + 0x000f0> in <filename unknown>:0 \n  at
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[]
parameters) <0x7f95a3fff0 + 0x0003b> in <filename unknown>:0 \n  at
UXDivers.Artina.Player.Platform.XamlLoader+<XamlLoader>c__AnonStorey0.<>m__0
(Xamarin.Forms.BindableObject view, System.String xaml) <0x7f912ef7a8 +
0x00097> in <filename unknown>:0 \n  at
UXDivers.Artina.Player.Platform.XamlLoader.LoadFromXaml[TView]
(UXDivers.Artina.Player.Platform.TView view, System.String xaml)
<0x7f912ef730 + 0x0003f> in <filename unknown>:0 \n  at
UXDivers.Artina.Player.Coordinator.CreatePage (System.String fullClassName,
System.String assemblyName, System.String xaml) <0x7f912ef3b8 + 0x001f3> in
<filename unknown>:0 \n  at
UXDivers.Artina.Player.Coordinator.BuildXamlPage (System.String xaml,
UXDivers.Artina.Player.PayloadBase payload) <0x7f912eedc0 + 0x00287> in
<filename unknown>:0 \n  at
UXDivers.Artina.Player.Coordinator+<TargetUpdatedMessageHandler>c__AnonStorey3.<>m__0
() <0x7f912ed228 + 0x00c8f> in <filename unknown>:0 ,
NonExceptionType=null,
IsTerminating=false\n","timestamp":"2016-02-12T11:08:08.858Z"}


2016-02-12 12:03 GMT+01:00 jpbrocca <notifications@github.com>:

**Comment by jpbrocca** [comment]
OK, we will need to investigate more on this issue.
Thank you!

**Comment by jpbrocca** [comment]
Closing this since it was resolved. I created a new issue #39 for the problem being reported.
