### ISSUE TITLE
XAML: One of the identified items was in an invalid format.

### ISSUE THREAD

**Issue by jpbrocca** [UXDivers/Gorilla-Player-Support-And-Issues#39]
Moving #37 reported by @WillemMali to this issue.

**Comment by jpbrocca** [comment]
The error the app gave me was "XAML: One of the identified items was in an
invalid format."

The XAML for the page is:

<?xml version="1.0" encoding="utf-8" ?>
<ContentPage
    xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    x:Class="Test.TestView1"
    Title="Test">
    <Grid>
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="*" />
            <ColumnDefinition Width="*" />
            <ColumnDefinition Width="*" />
            <ColumnDefinition Width="*" />
            <ColumnDefinition Width="*" />
            <ColumnDefinition Width="*" />
        </Grid.ColumnDefinitions>
        <Grid.RowDefinitions>
            <RowDefinition Height="*" />
            <RowDefinition Height="80%" />
            <RowDefinition Height="*" />
        </Grid.RowDefinitions>
        <Button Grid.Column="0" Grid.Row="0" Grid.ColumnSpan="2"></Button>
        <Button Grid.Column="2" Grid.Row="0" Grid.ColumnSpan="2"></Button>
        <Button Grid.Column="4" Grid.Row="0" Grid.ColumnSpan="2"></Button>
    </Grid>
</ContentPage>

The Grid element seems to be the one crashing your compiler; if you
removethe Grid.ColumnDefinitions and Grid.RowDefinitions (and everything
inside) it still crashes.

The relevant line in the log is this:

{"level":"error","message":"Gorilla Server: error: Client reported error
Sender=null, When={0:02/12/16 12:07:52 +01:00}, Context=XAML: One of the
identified items was in an invalid format., ExceptionMessage=Exception has
been thrown by the target of an invocation.,
ExceptionType=System.Reflection.TargetInvocationException,
ExceptionStackTrace=  at System.Reflection.MonoMethod.Invoke (System.Object
obj, BindingFlags invokeAttr, System.Reflection.Binder binder,
System.Object[] parameters, System.Globalization.CultureInfo culture)
<0x7f95a40040 + 0x000f0> in <filename unknown>:0 \n  at
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[]
parameters) <0x7f95a3fff0 + 0x0003b> in <filename unknown>:0 \n  at
UXDivers.Artina.Player.Platform.XamlLoader+<XamlLoader>c__AnonStorey0.<>m__0
(Xamarin.Forms.BindableObject view, System.String xaml) <0x7f912ef7a8 +
0x00097> in <filename unknown>:0 \n  at
UXDivers.Artina.Player.Platform.XamlLoader.LoadFromXaml[TView]
(UXDivers.Artina.Player.Platform.TView view, System.String xaml)
<0x7f912ef730 + 0x0003f> in <filename unknown>:0 \n  at
UXDivers.Artina.Player.Coordinator.CreatePage (System.String fullClassName,
System.String assemblyName, System.String xaml) <0x7f912ef3b8 + 0x001f3> in
<filename unknown>:0 \n  at
UXDivers.Artina.Player.Coordinator.BuildXamlPage (System.String xaml,
UXDivers.Artina.Player.PayloadBase payload) <0x7f912eedc0 + 0x00287> in
<filename unknown>:0 \n  at
UXDivers.Artina.Player.Coordinator+<TargetUpdatedMessageHandler>c__AnonStorey3.<>m__0
() <0x7f912ed228 + 0x00c8f> in <filename unknown>:0 ,
NonExceptionType=null,
IsTerminating=false\n","timestamp":"2016-02-12T11:08:08.858Z"}

**Comment by WillemMali** [comment]
I'd be very interested in seeing this fixed as this currently stops me from being able to use Gorilla Player for most of my app. If there's anything I can do to help I'd be glad to.

**Comment by jpbrocca** [comment]
Hi @WillemMali,

It seems the XAML code from your sample is invalid and that is why Gorilla cannot preview the page.

You are using "%" for the grid units which is not valid.
You should use any of the available units:

- **Absolute:** Sets the cell’s size equal to the number of device-specific-units (dpu). 
- **Auto:** Sets the cell’s size equal to its content. 
- **Star:** Sets the cell’s size equal to a proportion of the remaining space after all the cells with Absolute and Auto definitions are placed

You should replace the "%" with "*" and then you will get the preview on Gorilla.

Thanks,
JP

**Comment by WillemMali** [comment]
Hi @jpbrocca,

Thanks for pointing that out, and sorry for wasting your time.
I just found out XAML errors manifest as reflection exceptions, which is
why I didn't think to look at the XAML before.

Anyway, it's working now!

Thanks,
Willem

2016-02-15 10:13 GMT+01:00 jpbrocca <notifications@github.com>:

**Comment by jpbrocca** [comment]
Hi @WillemMali, no worries ;)

Don´t hesitate to write if you find anything that you do not understand or if is something "suspicious".
You are helping us making a better product, so I should say thanks :)

Best,
JP
