### ISSUE TITLE
Gorilla player - unable to preview ContentView XAML file

### ISSUE THREAD

**Issue by jsinh** [UXDivers/Gorilla-Player-Support-And-Issues#4]
Gorilla player at the moment only supports previewing of XAML files which has ContentPage as base class / main layout.

This mean if your XAML file inherits ContentView instead it won't get previewed in the player app.
You can easily confirm this by keeping the XAML file tab as active windows in Xamarin Studio on MAC. Go to > Tools > Gorilla Player > "Why can't target this XAML file?"

This gives a popup saying - 
> Only Xamarin Forms Pages can be set as Gorilla target. xyz.xaml was not recognized as a page (root XAML tag is ContentView).

Quick workaround to this limitation (which as per the team will go away soon) is create a empty XAML file with root XAML tag as ContentPage and add your ContentView page inside it.

This is a note for everyone using Gorilla player for XAML previewing.
Also a feature request to the team to show some love by supporting previewing of ContentView XAML files.

Thanks in advance.

**Comment by LeoHere** [comment]
Just want to let you know that ContentView preview will be available in the next update. Best
