### ISSUE TITLE
Gorilla player uninstaller doesn't uninstall VS or Xamarin plugin

### ISSUE THREAD

**Issue by WillemMali** [UXDivers/Gorilla-Player-Support-And-Issues#40]
Title says it all. It also seems like Xamarin Studio doesn't allow you to uninstall Gorilla Player in any way at all.

**Comment by jpbrocca** [comment]
Hi @WillemMali,

Do you get an error or something while uninstalling?

Did you make sure you closed Xamarin Studio and Visual Studio before you start uninstalling ?

If you could attach the log files (you will need to create a .zip file with them) that could help us to find the issue.

Thanks!
JP

**Comment by jpbrocca** [comment]
Sorry, my mistake.

Current version does not automatically uninstall the addins for Xamarin Studio and Visual Studio.
Those need to be manually uninstalled.

Let me know if you need help with that part.

Regards,
JP

**Comment by WillemMali** [comment]
Thanks, I just figured out where in Xamarin Studio I can uninstall plugins
(Tools - Add-In Manager).

2016-02-12 14:06 GMT+01:00 jpbrocca <notifications@github.com>:
