### ISSUE TITLE
Accidentally deleted the Gorilla App from Simulator

### ISSUE THREAD

**Issue by jbpoulsen** [UXDivers/Gorilla-Player-Support-And-Issues#42]
Hello!

First of all, I've had no problems with your awesome tool this far.
But today it started acting up, not showing the connected XAML and started failing when connecting using Xamarin Studio.

I therefore deleted the Gorilla App from my emulator to try and see if a full reinstall of Gorilla would fix my issue.

Problem is, after the full reinstallation of Gorilla Player (Mac) it didn't install the Gorilla App on the simulator.

This means that i can see my XAML pages in Xamarin Studio is connected correctly like so : MyPage.Xaml (Gorilla), but i cannot launch the App from the Simulator since its no longer available.
How do reinstall the Gorilla App on the simulator?

It might be a basic problem, but for me there seem to be no solution.
I have restarted Xamarin Studio and the Simulator several times after the reinstallation.

Thanks!

**Comment by jpbrocca** [comment]
Hi @jbpoulsen,

it seems you deleted Player app -the one that you deploy to your device/emulator-, right?

If that is the case, simply right click on Gorilla icon an open the walkthrough:

![image](https://cloud.githubusercontent.com/assets/15996999/13073452/a4392a28-d47d-11e5-9981-d819ba911bdc.png)

Then, go to step 2 and open the Player solution:

![image](https://cloud.githubusercontent.com/assets/15996999/13073503/dc7fffec-d47d-11e5-9813-135c62576cd7.png)

Then simply follow the procedure explained in the walkthrough to deploy the app.

Let me know how it goes.

Thanks,
JP

**Comment by jbpoulsen** [comment]
Oh man, how did i miss/forget that, embarrassing.

Ez pz, worked like a charm.

Have a great day!

**Comment by jpbrocca** [comment]
Hahaha...No worries ;)

Let me know if you need anything else.

Have a great day you too!
JP
