### ISSUE TITLE
Invalid reference breaks Gorilla

### ISSUE THREAD

**Issue by james-lavery** [UXDivers/Gorilla-Player-Support-And-Issues#7]
If a reference cannot be resolved in XAML, Gorilla breaks.

For example, in the following XAML snippet, the mismatch between the _x:Name="viewCell"_ for the ViewCell element, and the _x:Reference viewCel_ in the _CommandParameter_ causes Gorilla to crash rather than display a meaningful message to the user.

```xml
<ViewCell
	x:Name="viewCell">
	<StackLayout 
		Orientation="Horizontal">
		<Image
			Source="{Binding ThumbnailSource}" />
		<Label
			Text="{Binding Name}" VerticalOptions="Center"/>
		<Button
			Text            ="Play"
			BindingContext  ="{Binding Source={x:Reference mainView}, Path=BindingContext}"
			Command         ="{Binding PlayVideoCommand}"
			CommandParameter="{Binding Source={x:Reference viewCel}, Path=BindingContext}" />
	</StackLayout>
</ViewCell>					
```

**Comment by diego5** [comment]
Invalid References do not make Gorilla crash anymore.
