### ISSUE TITLE
If a content view is not found Gorilla crashes

### ISSUE THREAD

**Issue by jpbrocca** [UXDivers/Gorilla-Player-Support-And-Issues#9]
If a 
~~~
<ContenView>
~~~
is being referenced from a 
~~~
<ViewCell>
~~~
and:

* the referenced file name is wrong
* or if the file does not exist

...then Gorilla crashes:

![image](https://cloud.githubusercontent.com/assets/15996999/11974800/6c8cb912-a946-11e5-80a4-b73985888c89.png)

**Comment by LeoHere** [comment]
Fixed in 0.8.1
